### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by sneaker1** [kleros/archon#41]
Hello,

the module isn't working for me at all.
I get ReferenceError: self is not defined, when i just require the module.

Steps to reproduce:

1. Install the module in a fresh node project
`npm install @kleros/archon`

2. create a javascript file (archontest.js) with just one line:
`var Archon = require('@kleros/archon')`

3. Run the script:
`node archontest.js`

Here's what i get:
```
ReferenceError: self is not defined
    at Object.<anonymous> (/home/xxx/Programming/test/node_modules/@kleros/archon/dist/archon.bundle.js:2:194)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/matze/Programming/test/archontest.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)

```

**Comment by sneaker1** [comment]
Ok, I think i figured this out myself.

It needs to be run in the browser. Only running it with node results in the above error.
